# Generated by Django 2.1.1 on 2019-03-19 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='local',
            field=models.ManyToManyField(blank=True, null=True, to='producto.Local'),
        ),
    ]
